package com.jdc.ee8.ds;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.annotation.sql.DataSourceDefinition;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

@DataSourceDefinition(
		name = "java:app/AppDB",
		url = "jdbc:hsqldb:mem:appDB",
		user = "sa",
		password = "sa",
		className = "org.hsqldb.jdbc.JDBCPool")
@WebServlet(urlPatterns = "/students", loadOnStartup = 1)
public class StudentServlet extends HttpServlet{

	private static final long serialVersionUID = 1L;
	
	@Resource(lookup = "java:app/AppDB")
	private DataSource ds;
	
	@Override
	public void init() throws ServletException {
		
		try(Connection conn = ds.getConnection();
				Statement stmt = conn.createStatement()) {
			
			String sql = "create table STUDENT ("
					+ "id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, "
					+ "name VARCHAR(30), "
					+ "email VARCHAR(50));";
			
			stmt.executeUpdate(sql);
			
		} catch (Exception e) {
			e.printStackTrace();
		}

	}
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		
		String sql = "select * from STUDENT";
		List<StudentDTO> list = new ArrayList<>();
		
		try(Connection conn = ds.getConnection();
				PreparedStatement stmt = conn.prepareStatement(sql)) {
			
			ResultSet rs = stmt.executeQuery();
			
			while(rs.next()) {
				StudentDTO dto = new StudentDTO();
				dto.setId(rs.getInt(1));
				dto.setName(rs.getString(2));
				dto.setEmail(rs.getString(3));
				list.add(dto);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		req.setAttribute("list", list);
		getServletContext().getRequestDispatcher("/index.jsp").forward(req, resp);
	}
	
	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		
		String name = req.getParameter("name");
		String email = req.getParameter("email");
		
		String sql = "insert into STUDENT (name, email) values (?, ?)";
		
		try(Connection conn = ds.getConnection();
				PreparedStatement stmt = conn.prepareStatement(sql)) {
			
			stmt.setString(1, name);
			stmt.setString(2, email);
			
			stmt.executeUpdate();
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		resp.sendRedirect("students");
	}

}
